### PR TITLE
update versions for wdi8

### PR DESCRIPTION
**Pull request by mattscilipoti**
I choose the versions after running:
`brew update`
`rvm get latest`
`gem update --system`
`gem install bundler`
Used latest download from postgreapp.com

Did I miss anything?

Ruby, 2.2.3
ruby gems, 2.5.2
(added) bundler, 1.11.2
Git, 2.7.0
atom 1.4
postgres 9.5.0
xcode, 2343

### CODE REVIEW

**Comment by jshawl** [comment]
:+1:

**Comment by adambray** [comment]
:+1:

**Comment by RobertAKARobin** [comment]
@mattscilipoti I'm using Ruby 2.3.0. We don't want that?

**Comment by RobertAKARobin** [comment]
:+1:

**Pull request merged**
